"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Every setting below reads from the environment first, falling back to
# the original hardcoded dev values -- so `python manage.py runserver`
# with no env vars set behaves exactly as before, and only a deploy
# target (Render, in practice) needs to actually set anything.

# SECURITY WARNING: keep the secret key used in production secret!
# Render: set DJANGO_SECRET_KEY (render.yaml generates one automatically
# via `generateValue: true` -- see its own comment for why that's safe).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-$75wiw+t1hlts_dtd6@-@l_%peahu@de(+bfesfo=$ay-_2&vf"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Comma-separated, e.g. "budget-api.onrender.com,budget.example.com".
# RENDER_EXTERNAL_HOSTNAME is set automatically by Render itself (no
# manual config needed for the default *.onrender.com hostname); a
# custom domain still needs adding to DJANGO_ALLOWED_HOSTS by hand.
ALLOWED_HOSTS = [
    h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h
]
render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if render_host:
    ALLOWED_HOSTS.append(render_host)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "measures",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # gunicorn (unlike `manage.py runserver` in DEBUG mode) never serves
    # static files itself -- without this, DEBUG=False in production
    # would 404 on DRF's own browsable-API CSS/JS and the admin's
    # styling, even though the actual JSON endpoints work fine.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # measure_list's own JSON (a few thousand rows, fetched in full --
    # see its own docstring for why) is ~1.3MB uncompressed but ~195KB
    # gzipped, a 6.7x cut that matters a lot on a slow/proxied
    # connection. WhiteNoise's own compression above only covers static
    # files (JS/CSS), never API responses -- this is what actually
    # shrinks JSON. Django's GZipMiddleware compresses any response
    # >200 bytes whose client sends `Accept-Encoding: gzip` (every real
    # browser does); must sit before CommonMiddleware since it needs to
    # see the final response body.
    "django.middleware.gzip.GZipMiddleware",
    # No response under /api/ should ever be cached by the browser or an
    # intermediate proxy -- every one reflects live, request-specific
    # state (a search result, a $ figure). See its own docstring for the
    # concrete case this guards against.
    "measures.middleware.NoStoreApiMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Local dev origins always allowed; the deployed frontend's own origin
# (Render: the static site's *.onrender.com URL, or a custom domain) is
# added via DJANGO_CORS_ALLOWED_ORIGINS, comma-separated, e.g.
# "https://budget-frontend.onrender.com,https://budget.example.com".
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
] + [o for o in os.environ.get("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",") if o]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        # The existing programs.db built by build_db.py / build_measures_db.py,
        # one directory up from this Django project.
        "NAME": BASE_DIR.parent / "programs.db",
    }
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# `manage.py collectstatic` target -- see render.yaml's buildCommand.
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
